### ISSUE TITLE
decryption file issue when using latest version (0.5.0)

### ISSUE THREAD

**Issue by Vijay5056** [vsajip/python-gnupg#199]
We are getting below exception while decrypting the file in databricks. It was working fine with same code till yesterday. We have an issue today in both the subscription and all the environments (dit, QA, UAT and Prod).
Exception occured while decrypting file using pgp keys: decrypt_file() got an unexpected keyword argument 'file' /databricks/spark/python/pyspark/sql/session.py:387: UserWarning: inferring schema from dict is deprecated,please use pyspark.sql.Row instead warnings.warn("inferring schema from dict is deprecated,"

We have used the latest version (0.5.0). But, We got the above error. When we tried with 0.4.9 version, we were able to decrypt the file.

![image](https://user-images.githubusercontent.com/112416294/187248809-d1a7b349-cc70-4775-b38a-c477f51f17b7.png)

**Comment by vsajip** [comment]
You shouldn't be using keyword arguments to pass an argument which isn't a keyword argument. In this case, just call `decrypt_file(f, ...)` instead of `decrypt_file(file=f, ...)`.

The positional argument `file` was recently changed to `fileobj_or_path` to allow a path to be passed in as well as a file-like object. (This applies to other functions in the API, too, so check your other usages.)
