### ISSUE TITLE
Questions on using smart cards

### ISSUE THREAD

**Issue by itssme** [vsajip/python-gnupg#220]
I have a question regarding the use of smart cards (specifically a yubikey 4c) with this software. 

Usually I would do:
```
> gpg --card-edit
general information about the smartcard etc.
gpg/card> list keys
output of keys etc.
```

And then I can generate keys on the smartcard etc. But how could I use this software to do this using python? I have tried adding the "--card-edit" option as option parameter, but then list keys does not give me any keys at all:
```
>>> import gnupg
>>> gpg = gnupg.GPG(options=['--card-edit'])
>>> pg.list_keys()
[]
```

Am I doing something wrong/ missing some option to specify, that I want to use a smart card? Any help is appreciated!

**Comment by vsajip** [comment]
In general, `python-gnupg` doesn't support any functionality which requires back-and-forth interaction with `gpg` (for example, editing keys). That's because:

* You'd need a state machine to handle all possible interactions reliably, and that's quite a lot of work
* The state machine would need to be version-aware, because `gpg` changes behaviour in this kind of area across versions not infrequently - even more work, and an ongoing support burden
* `gpg` itself isn't designed to support such interaction, so support from upstream with diagnosing/fixing issues is likely to be absent or not timely
