### ISSUE TITLE
python gnupg version 0.5.0 giving error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by deblinadass** [vsajip/python-gnupg#233]
Earlier Scenario : We were using python-gnupg 0.5.0 with bionic beaver platform & everything were working fine. 

Current Scenario : We were using python-gnupg 0.5.0 with Jammy Jellyfish platform & getting below error 
Error : ValueError: Error invoking gpg: 127: /home/vcap/app/gpg/gpg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory.

We have gpg file set in our application but still getting error.  Attached the screenshot of this error.

![MicrosoftTeams-image (59)](https://github.com/vsajip/python-gnupg/assets/30339739/b9771658-086f-4270-8e61-270d3fb1cc64)

**Comment by vsajip** [comment]
This is an error returned by your executable `/home/vcap/app/gpg/gpg`, which is entirely a program that you control. You will need to raise this error with the `GnuPG` project, which is on [their dev site](https://dev.gnupg.org/). If you turn on logging in your Python code for the `gnupg` module (the above doesn't show this being enabled) you will see the command line that `python-gnupg` uses to invoke `gpg`. What happens when you run the command where the error occurs (not _exactly_ the same, but using the logs as a basis) directly from the command line?

From what I've seen so far, it doesn't look like a bug in `python-gnupg`.

**Comment by deblinadass** [comment]
it's resolved by changing gpgbinary path to /usr/bin/gpg1
